@startuml

scale 0.75

participant  ":ExchangeRateRequest"
participant  ":OrgStructureAndRegionRequest"
participant  ":CassandraConnection"
participant  ":keySet"
participant  ":Collection"
participant  ":BaseStream"
participant  ":Stream"
participant  ":Arrays"
participant  ":SalesRequest"
participant  ":KpiRequest"

":ExchangeRateRequest" -[#0000FF]> ":CassandraConnection" : getConnection()
":OrgStructureAndRegionRequest" -[#0000FF]> ":CassandraConnection" : getConnection()
":CassandraConnection" --[#FF00CB]> ":OrgStructureAndRegionRequest" : Connection
":CassandraConnection" --[#FF00CB]> ":ExchangeRateRequest" : Connection
":ExchangeRateRequest" -[#0000FF]> ":ExchangeRateRequest" : new ExchangeRateRequest()
":ExchangeRateRequest" --[#FF00CB]> ":ExchangeRateRequest" : new ExchangeRateRequest

":OrgStructureAndRegionRequest" -[#0000FF]> ":OrgStructureAndRegionRequest" : getPmgAndRegionsFromSales()
":OrgStructureAndRegionRequest" --[#FF00CB]> ":OrgStructureAndRegionRequest" : PmgAndRegionsFromSales
":OrgStructureAndRegionRequest" -[#0000FF]> ":keySet" : keySet()
":keySet" -[#0000FF]> ":Collection" : stream()

":Collection" -[#0000FF]> ":BaseStream" : parallel()
":BaseStream" -[#0000FF]> ":Stream" : flatMap()
":Stream" -[#0000FF]> ":Arrays" : stream()
":Arrays" -[#0000FF]> ":SalesRequest" : flatMap()

":SalesRequest" -[#0000FF]> ":SalesRequest" : new SalesRequest()
":SalesRequest" --[#FF00CB]> ":SalesRequest" : new SalesRequest
":SalesRequest" -[#0000FF]> ":KpiRequest" : calculateKpis()
":KpiRequest" --[#FF00CB]> ":SalesRequest" : salesType
":SalesRequest" --[#FF00CB]> ":Arrays" : salesType
":Arrays" --[#FF00CB]> ":BaseStream" : region
":BaseStream" --[#FF00CB]> ":OrgStructureAndRegionRequest" : product





@enduml