@startuml

hide footbox
title __Sequenzdiagramm für die Methoden__\n\n


participant  ":ForecastWS"
participant  ":SalesService"
participant  ":FixedCostsService"
participant  ":ExchangeRateRequest"
participant  ":SalesRequest"
participant  ":FixedCostsRequest"
participant  ":KpiRequest"
participant  ":Stream"



":ForecastWS" -[#0000FF]> ":SalesService" : getSalesKPIs(planPeriod, currentPeriod, curr)
group getSalesKPIs()
":SalesService" -[#0000FF]> ":ExchangeRateRequest" : new ExchangeRateRequest(getConnection(), toCurrency)
":ExchangeRateRequest" --[#FF00FF]> ":SalesService" : new ExchangeRateRequest
":SalesService" -[#0000FF]> ":SalesRequest" : new SalesRequest(getConnection())
":SalesRequest" --[#FF00FF]> ":SalesService" : new SalesRequest
":SalesService" -[#0000FF]> ":SalesRequest" : getPmgAndRegions()
":SalesRequest" --[#FF00FF]> ":SalesService" : Map<String, Set<String>>
loop parallel
    ":SalesService" -[#0000FF]> ":KpiRequest": calculateKpis()
    ":KpiRequest" --[#FF00FF]> ":SalesService" : Stream<OutputDataType>
end
":SalesService" --[#FF00FF]> ":ForecastWS" : Stream<salesKpis>
end

":ForecastWS" -[#0000FF]> ":FixedCostsService" : getFixedCostsKpis(planPeriod, currentPeriod, curr)
group getFixedCostsKpis()
":FixedCostsService" -[#0000FF]> ":ExchangeRateRequest" : new ExchangeRateRequest(getConnection(), toCurrency)
":ExchangeRateRequest" --[#FF00FF]> ":FixedCostsService" : new ExchangeRateRequest
":FixedCostsService" -[#0000FF]> ":FixedCostsRequest" : FixedCostsRequest(getConnection())
":FixedCostsRequest" --[#FF00FF]> ":FixedCostsService" : new FixedCostsRequest
":FixedCostsService" -[#0000FF]> ":FixedCostsRequest" : getSubregionsAndSbu()
":FixedCostsRequest" --[#FF00FF]> ":FixedCostsService" : Map<String, Set<String>>
loop parallel
    ":FixedCostsService" -[#0000FF]> ":KpiRequest": calculateKpis()
    ":KpiRequest" --[#FF00FF]> ":FixedCostsService" : Stream<OutputDataType>
end
":FixedCostsService" --[#FF00FF]> ":ForecastWS" : Stream<fixedCostsKpis>
end

":ForecastWS" -[#0000FF]> ":Stream" : concat(salesKpis, fixedCostsKpis)
":Stream" -[#0000FF]> ":Stream" : sorted(new OutputDataTypeComparator())
":Stream" -[#0000FF]> ":Stream" : collect()
":Stream" --[#FF00FF]> ":ForecastWS" : List<OutputDataType>
@enduml