@startuml

hide footbox
'title Sequenzdiagramm: Overall Picture

participant ":Client"
participant ":Environment"
participant ":Database"

":Client" -[#0000FF]> ":Environment": HTTP Request

alt if request not valid
":Environment" --[#FF00FF]> ":Client": refuse
else else
":Environment" -[#0000FF]> ":Environment": parse request
end

":Environment" -[#0000FF]> ":Database": send request
":Database" -[#0000FF]> ":Database": work on
":Database" --[#FF00FF]> ":Environment": iterable of results
":Environment" --[#FF00FF]> ":Client": HTTP response(JSON)

@enduml