@startuml


participant  ":ForecastWS"
participant  ":SalesService"
participant  ":FixedCostsService"
participant  ":ExchangeRateRequest"
participant  ":OrgStructureAndRegionRequest"
participant  ":SalesRequest"
participant  ":KpiRequest"

":ForecastWS" -> ":SalesService" : getSalesKPIs(planPeriod, currentPeriod, curr)
":SalesService" -> ":ExchangeRateRequest" : new ExchangeRateRequest(getConnection(), toCurrency)
":ExchangeRateRequest" --> ":SalesService" : new ExchangeRateRequest
":SalesService" ->  ":OrgStructureAndRegionRequest" : new OrgStructureAndRegionRequest(getConnection())
":OrgStructureAndRegionRequest" --> ":SalesService" : new OrgStructureAndRegionRequest
":SalesService" ->  ":SalesRequest" : new SalesRequest(getConnection())
":SalesRequest" --> ":SalesService" : new SalesRequest
":SalesService" -> ":SalesRequest" : getPmgAndRegions()
":SalesRequest" --> ":SalesService" : Map<String, Set<String>>
par
    ":SalesService" -> ":SalesRequest": stream().parallel()
    loop
        ":SalesRequest" -> ":KpiRequest" : calculateKpis()
        ":KpiRequest"  --> ":SalesRequest" : Stream<OutputDataType>
    end
    ":SalesRequest" --> ":SalesService" : Stream<OutputDataType>
end

":SalesService" --> ":ForecastWS" : Stream<OutputDataType>



":ForecastWS" -> ":FixedCostsService" : getFixedCostsKpis(planPeriod, currentPeriod, curr)
":FixedCostsService" -> ":ExchangeRateRequest" : new ExchangeRateRequest(getConnection(), toCurrency)
":ExchangeRateRequest" --> ":FixedCostsService" : new ExchangeRateRequest
":FixedCostsService" ->  ":OrgStructureAndRegionRequest" : new OrgStructureAndRegionRequest(getConnection())
":OrgStructureAndRegionRequest" --> ":FixedCostsService" : new OrgStructureAndRegionRequest
":FixedCostsService" -> ":FixedCostsRequest" : FixedCostsRequest(getConnection())
":FixedCostsRequest" --> ":FixedCostsService" : new FixedCostsRequest
":FixedCostsService" -> ":FixedCostsRequest" : getSubregionsAndSbu()









@enduml