@startuml


participant  ":ForecastWS"
participant  ":SalesService"
participant  ":ExchangeRateRequest"
participant  ":OrgStructureAndRegionRequest"
participant  ":SalesRequest"
participant  ":FixedCostsService"
participant  ":Stream"
participant  ":KpiRequest"


":ForecastWS" -> ":SalesService" : getSalesKPIs(planPeriod, currentPeriod, curr)
":SalesService" -> ":ExchangeRateRequest" : new ExchangeRateRequest(getConnection(), toCurrency)
":ExchangeRateRequest" --> ":SalesService" : new ExchangeRateRequest
":SalesService" ->  ":OrgStructureAndRegionRequest" : new OrgStructureAndRegionRequest(getConnection())
":OrgStructureAndRegionRequest" --> ":SalesService" : new OrgStructureAndRegionRequest
":SalesService" ->  ":SalesRequest" : new SalesRequest(getConnection())
":SalesRequest" --> ":SalesService" : new SalesRequest
":SalesRequest" -> ":SalesRequest" : getPmgAndRegions()
":SalesRequest" --> ":SalesRequest" : Map<String, Set<String>>
":SalesService" -> ":KpiRequest" : calculateKpis()
":KpiRequest"  --> ":SalesService" : Stream<OutputDataType>










@enduml