@startuml

hide footbox
'title Sequenzdiagramm: Overall Picture

participant ":Client"
participant ":Environment"
participant ":Database"

":Client" -> ":Environment": HTTP Request

alt if request not valid
":Environment" -> ":Client": refuse
else else
":Environment" -> ":Environment": parse request
end

":Environment" --> ":Database": send request
":Database" -> ":Database": work on
":Database" -> ":Environment": iterable of results
":Environment" -> ":Client": HTTP response(JSON)

@enduml