@startuml

node "<<executionEnvironment>\n :__Laufzeitumgebung__" as LZ{

    node "fourschlag.war"{

        folder "importer"{
                artifact "config.json"
                artifact "importMain.py"
            }

        folder "jmeter"{
                    artifact "FourschlagTest.jmx"
            }

        folder "libs"{

            folder "Webservice Drivers"{
                artifact "jackson-jaxrs-base"
                artifact "jackson-jaxrs-json-provider"
                artifact "jackson-jaxrs-providers"
                artifact "jersey-container-servlet"
            }

            folder "Cassandra Drivers"{
                artifact "cassandra-driver-core"
                artifact "cassandra-driver-extras"
                artifact "cassandra-driver-mapping"
            }

        }

        folder "src"{
            folder "services"
            folder "entities"
        }

        folder "web"{
            folder "frontend"
            folder "WEB-INF"
            artifact "index.jsp"
        }
    }
}

node "<<device>\n :__Datenbankserver 1...n, Linux__" as N1{

    database "<<database>>\n :Apache Cassandra" as Cassandra2
}

 node "<<device>\n __:Rechner, Service Nutzer__" as N2{

        artifact "WS-fähige Bibliothek"
 }


LZ == N1: <<Cassandra´s Binary Protocol>>
LZ =up= N2: <<HTTP>>


@enduml