@startuml
/' For available options see
http://plantuml.com/component-diagram
http://plantuml.com/class-diagram '/

title
 <b>Class diagram of <u>FourSchlag</u> project</b>
 <i>Description:</i> Reduced package / class dependencies of <i>SALES</i> KPI calculations
 <i>Version:</i> <b>DRAFT</b>, 14th Nov 2016
 <i>Author:</i> Steffen Wagner
end title

left to right direction

package "fourschlag" {
    package "entities" {
        package "accessors" {
            Interface "ActualSalesAccessor"{
            }

            Interface "ExchangeRateAccessor" {
            }

            Interface "ForecastSalesAccessor" {
            }

            Interface "OrgStructureAccessor" {
            }

            Interface "RegionAccessor" {
            }
        }

        package "types" {
            Enum "DataSource" {
            }

            Enum "EntryType" {
            }

            Enum "KeyPerformanceIndicators" {
            }

            Class "OutputDataType" {
            }

            Class "Period" {
            }

            Enum "SalesType" {
            }
        }

        package "tables" {
            Class "ActualFixedCostsEntity" {
            }

            Class "ActualSalesEntity" {
            }

            Class "ExchangeRateEntity" {
            }

            Class "ForecastFixedCostsEntity" {
            }

            Class "ForecastSalesEntity" {
            }

            Class "OrgStructureEntity" {
            }

            Class "RegionEntity" {
            }

            Class "SalesEntity" {
            }
        }

        ' inheritances from SalesEntity
        SalesEntity <|-- ForecastSalesEntity
        SalesEntity <|-- ActualSalesEntity

        ' create usages from Accessors to different Entities
        ActualSalesAccessor *-- ActualSalesEntity : use
        ExchangeRateAccessor *-- ExchangeRateEntity : use
        ForecastSalesAccessor *-- ForecastSalesEntity : use
        OrgStructureAccessor *-- OrgStructureEntity : use
        RegionAccessor *-- RegionEntity : use
    }

    package "services" {

        package "data" {

            package "requests" {
                Class "ExchangeRateRequest" {
                    +double : getExchangeRate()
                    +String : getToCurrency()
                }

                Class "KpiRequests" {

                }

                Class "OrgStructureRequest" {
                    +Result<OrgStructureEntity> : getProductMainGroups()
                }

                Class "RegionRequest" {
                     +Result<RegionEntity> : getSubregions()
                     +Set<String> : getRegions()
                }

                Class "Request" {
                    +Session : getSession()
                    +MappingManager : getManager()
                }

                Class "SalesRequest" {
                    +List<OutputDataType>: getSalesKpis()
                }

                ' inheritance of Request <-- KpiRequest <-- SalesRequest
                Request <|-- KpiRequests
                KpiRequests <|-- SalesRequest

                ' inherits for Request
                Request <|-- OrgStructureRequest
                Request <|-- RegionRequest

                ' ExchangeRateRequest gets data from ExchangeRateAccessor
                ExchangeRateRequest *-- ExchangeRateAccessor : use

                ' KpiRequests uses KPI class
                KpiRequests *-- KeyPerformanceIndicators : use

                ' usages from SalesRequest
                SalesRequest *-- ActualSalesAccessor : use
                SalesRequest *-- ForecastSalesAccessor : use
                SalesRequest *-- ExchangeRateRequest : use
                SalesRequest *-- KeyPerformanceIndicators : use
            }

            Class "Service" {
                +CassandraConnection : getConnection()
                +{static}int : getNumberOfMonths()
            }

            Class "SalesService" {
                +List<OutputDataType> : getSalesKPIs()
            }

            Service <|-- SalesService

            ' internal uses of SalesService
            SalesService *-- SalesRequest : use
            SalesService *-- ExchangeRateRequest : use
            SalesService *-- OrgStructureRequest : use
            SalesService *-- RegionRequest : use
            SalesService *-- Period : use
            SalesService *-- OutputDataType : use
            SalesService *-- SalesType : use
        }

        package "db" {
            Enum "KeyspaceNames" {
                +String : getKeyspace()
            }

            Enum "ClusterEndpoints" {
                +String : getAddress()
            }

            Class "CassandraConnection" {
                +Session : getSession()
                +MappingManager : getManager()
                +void : closeConnection()
            }

            ' internal uses of CassandaConnection
            CassandraConnection *-- KeyspaceNames : use
            CassandraConnection *-- ClusterEndpoints : use

            ' open database connection
            Service *-- CassandraConnection : use
        }

        package "web" {
            package "ws" {
                Class ForecastWS {
                    +Response : getSalesKPIs
                }
            }

            Class ApplicationService<? extends Application>  {
            }

            ApplicationService -- ForecastWS

            ' WS uses SalesService to get the KPI data
            ForecastWS *-- SalesService : use
            ForecastWS *-- CassandraConnection : use
        }
    }
}

@enduml