@startuml

scale 0.75

node ":__Laufzeitumgebung__" as LZ <<executionEnvironment>> {

    package "fourschlag.war" <<package>>{

        'package "jmeter"{
        '   artifact "FourschlagTest.jmx" <<artifact>>
        '}

        artifact "pom.xml" <<artifact>>{

            artifact "Webservice Drivers" <<artifact>>{
                artifact "jackson-jaxrs-base" <<artifact>>
                artifact "jackson-jaxrs-json-provider" <<artifact>>
                artifact "jackson-jaxrs-providers" <<artifact>>
                artifact "jersey-container-servlet" <<artifact>>
                artifact "slf4j-api" <<artifact>>
            }

            artifact "Cassandra Drivers" <<artifact>>{
                artifact "cassandra-driver-core" <<artifact>>
                artifact "cassandra-driver-extras" <<artifact>>
                artifact "cassandra-driver-mapping" <<artifact>>
            }
        }

        package "src" <<package>>{
            package "services"
            package "entities"

        }

        package "web" <<package>>{
            package "frontend"
            package "WEB-INF"
            artifact "index.jsp" <<artifact>>
        }
    }
}

node "__:Rechner, Service Nutzer__" as N2 <<device>>{

        artifact "WS-fähige Bibliothek" <<artifact>>
 }

node ":__Datenbankserver 1...n, Linux__" as N1 <<device>>{

    package "importer"{
        artifact "config.json" <<artifact>>
        artifact "importMain.py" <<artifact>>
    }
    database ":Apache Cassandra" as Cassandra <<database>>
}

LZ == N1: <<Cassandra´s Binary Protocol>>
LZ =up= N2: <<HTTP>>

@enduml