@startuml
left to right direction
skinparam packageStyle rect
skinparam monochrome true
scale 1.5

actor Admin

rectangle "<<actor>>\n Anwendung" as Anwendung

rectangle "DB System" as DBSystem {
	(Daten importieren)
	(Daten abfragen)
	(Daten manipulieren)
	(Daten exportieren)
}

Admin -right- (Daten importieren)
Admin -right- (Daten manipulieren)
Admin -right- (Daten abfragen)
Admin -right- (Daten exportieren)

Anwendung -left- (Daten importieren)
Anwendung -left- (Daten manipulieren)
Anwendung -left- (Daten abfragen)
Anwendung -left- (Daten exportieren)

@enduml